package at.ac.tuwien.dsg.hcu.monitor
 
import at.ac.tuwien.dsg.hcu.monitor.stream.*;
import at.ac.tuwien.dsg.hcu.monitor.action.*;

/**
 * RULES FOR HIGH UTILIZATION
 */
rule "MaxUtilViolated"
no-loop true
    when
        collectiveStream : CollectiveStream(metricName=="utilization", metricValue>=0.2)
    then
        Action.handleUtilizationOverload(collectiveStream.getCollective(), collectiveStream.getMetricValue());
end

